name: Website Deployment pipeline
on:
    pull_request:
        branches:
            - main
            - dev
            - staging
            - production
jobs:
    Deploy-to-S3:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Sync files to S3 bucket
              run: |
                aws s3 sync ./webapp s3://${{ secrets.S3_BUCKET_NAME }} --delete

            - name: Invalidate CloudFront Cache
              run: |
                  aws cloudfront create-invalidation \
                    --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} \
                    --paths "/*"