name: Website Deployment pipeline
on:
    pull_request:
        branches:
            - main
            - dev
            - staging
            - production
jobs:
  Provisioning:
    name: Provision Infrastructure
    uses: ./.github/workflows/Provision.yml
    secrets: inherit

  S3_Deployment:
    name: Deploy to AWS S3
    if: ${{vars.CLOUDFRONT_DISTRIBUTION_ID != 'empty'}}
    uses: ./.github/workflows/AWS_deploy.yml
    secrets: inherit
    

    
